### ISSUE TITLE
[refactor] : create a blueprint for the propoganda route and register to the app 

### ISSUE THREAD

**Issue by prathikshetty2002** [prathikshetty2002/Cybode#16]
do the following things to accomplish the task

- [x] create a file `propaganda.py` inside `api.cybode.com/routes/news/` directory
- [x] find the route for propaganda in `app.py` and copy that to `propaganda.py`
- [x] create a blueprint for this route and register it inside `app.py` file

**Comment by asim-vaibhav-435** [comment]
I want to work on this issue.

**Comment by prathikshetty2002** [comment]
@asim-vaibhav-435 you have been assigned this issue, make sure to create a seperate branch on your fork such as refactor-propaganda and keep your fork updated to upstream via syncing the staging branch and looking out for active changes. LFG

**Comment by prathikshetty2002** [comment]
Amazing this is done iin #23
